/**
 * =====================================================================
 * SERVICENOW FLUENT INTEGRATION: Siveillance_Intrusion
 * =====================================================================
 * 
 * PURPOSE:
 * This file defines the ServiceNow Fluent metadata for the Siveillance_Intrusion integration.
 * It creates table structures, field definitions, and relationships required
 * for storing and managing integration data within the CMDB.
 * 
 * SCOPE: x_ic_siveillance
 * VERSION: 1.0.0
 * PRIMARY TABLE: cmdb_ci_ot_siveillance_intrusion
 * 
 * GENERATED BY: InfinitiCode Integration Platform
 * 
 * =====================================================================
 * FILE STRUCTURE:
 * =====================================================================
 * 
 * 1. Application Definition
 *    - Declares the scoped application container
 *    - Sets up the application namespace
 * 
 * 2. Table Definition
 *    - Defines the primary CMDB CI table
 *    - Specifies parent class inheritance
 *    - Configures table-level properties
 * 
 * 3. Field Definitions
 *    - Creates custom fields for integration data
 *    - Sets field types, labels, and constraints
 *    - Defines mandatory fields and defaults
 * 
 * 4. Relationships
 *    - Establishes parent-child relationships
 *    - Defines reference fields to other tables
 *    - Configures relationship cardinality
 * 
 * 5. Behaviors
 *    - Attaches business rules and workflows
 *    - Defines validation logic
 *    - Configures lifecycle hooks
 * 
 * =====================================================================
 * USAGE:
 * =====================================================================
 * 
 * This file is processed by the ServiceNow Fluent compiler during
 * application build. The compiler generates:
 * 
 * - Table dictionary entries
 * - Field definitions with proper types
 * - ACL rules for scoped access
 * - UI components (forms, lists)
 * - Related server-side artifacts
 * 
 * DO NOT modify this file manually after generation unless you are
 * familiar with ServiceNow Fluent DSL syntax and conventions.
 * 
 * =====================================================================
 * MODIFICATION HISTORY:
 * =====================================================================
 * 
 * 2026-02-02 - Initial generation
 * 
 * =====================================================================
 */

/*
* Quality Report (static checks on generated code)
* No issues detected by static checks.
*/

/**
 * SERVICENOW FLUENT INTEGRATION
 * 
 * This file defines the complete table structure and fields for Siveillance_Intrusion.
 * The Fluent compiler will create the table and all fields when you click Publish in Studio.
 */

application('x_ic_siveillance', (app) => {
  /**
   * TABLE: cmdb_ci_ot_siveillance_intrusion
   * Extends: cmdb_ci_ot_field_device
   * 
   * This table inherits all standard OT device fields and adds integration-specific columns.
   */
  app.table('cmdb_ci_ot_siveillance_intrusion', (t) => {
    // Extend OT Field Device base class
    t.extends('cmdb_ci_ot_field_device');
    
    // Integration-specific fields
    // systemId: Unique system identifier
    t.field('systemid', {
      type: 'string',
      label: 'systemId',
      mandatory: false
    });

    // systemName: Human-readable system name
    t.field('systemname', {
      type: 'string',
      label: 'systemName',
      mandatory: false
    });

    // systemVersion: Siveillance system software version
    t.field('systemversion', {
      type: 'string',
      label: 'systemVersion',
      mandatory: false
    });

    // kernelVersion: System kernel version
    t.field('kernelversion', {
      type: 'string',
      label: 'kernelVersion',
      mandatory: false
    });

    // equipmentNumber: Physical equipment serial number
    t.field('equipmentnumber', {
      type: 'string',
      label: 'equipmentNumber',
      mandatory: false
    });

    // countryCode: ISO country code
    t.field('countrycode', {
      type: 'string',
      label: 'countryCode',
      mandatory: false
    });

    // systemStatus: Current operational status (Connected, Disconnected, Unknown)
    t.field('systemstatus', {
      type: 'string',
      label: 'systemStatus',
      mandatory: false
    });

    // busAmount: Number of communication buses
    t.field('busamount', {
      type: 'integer',
      label: 'busAmount',
      mandatory: false
    });

    // controlPanelCount: Number of control panels
    t.field('controlpanelcount', {
      type: 'integer',
      label: 'controlPanelCount',
      mandatory: false
    });

    // deviceCount: Total connected devices
    t.field('devicecount', {
      type: 'integer',
      label: 'deviceCount',
      mandatory: false
    });

    // inputCount: Total sensor inputs
    t.field('inputcount', {
      type: 'integer',
      label: 'inputCount',
      mandatory: false
    });

    // outputCount: Total control outputs
    t.field('outputcount', {
      type: 'integer',
      label: 'outputCount',
      mandatory: false
    });

    // areaCount: Total protected areas
    t.field('areacount', {
      type: 'integer',
      label: 'areaCount',
      mandatory: false
    });

    // lastSystemStart: Timestamp of last system restart
    t.field('lastsystemstart', {
      type: 'glide_date_time',
      label: 'lastSystemStart',
      mandatory: false
    });

    // licenseDateUtc: System license expiration date
    t.field('licensedateutc', {
      type: 'glide_date_time',
      label: 'licenseDateUtc',
      mandatory: false
    });

    // availableDiskKb: Available disk storage in kilobytes
    t.field('availablediskkb', {
      type: 'integer',
      label: 'availableDiskKb',
      mandatory: false
    });

    // availableFlashKb: Available flash memory in kilobytes
    t.field('availableflashkb', {
      type: 'integer',
      label: 'availableFlashKb',
      mandatory: false
    });
  });
});
/**
 * =====================================================================
 * END OF FLUENT FILE
 * =====================================================================
 * 
 * This completes the Fluent metadata definition for Siveillance_Intrusion.
 * 
 * NEXT STEPS AFTER INSTALLATION:
 * 
 * 1. VERIFY INSTALLATION
 *    - Check System Logs for [Installer] entries
 *    - Confirm all tables were created successfully
 *    - Verify system properties are set correctly
 * 
 * 2. CONFIGURE THE INTEGRATION
 *    - Open the Guided Setup wizard
 *    - Review and update configuration values
 *    - Test connectivity to external systems
 * 
 * 3. VALIDATE FUNCTIONALITY
 *    - Run manual test executions
 *    - Verify data is written to correct tables
 *    - Check scheduled jobs are running (if applicable)
 *    - Test webhook endpoints (if applicable)
 * 
 * 4. MONITOR PERFORMANCE
 *    - Review execution logs regularly
 *    - Check for rate limit warnings
 *    - Monitor retry attempts and failures
 *    - Track data reconciliation success rates
 * 
 * TROUBLESHOOTING:
 * 
 * If installation failed:
 *    - Search System Logs for errors tagged [Installer]
 *    - Review the error message in the result object
 *    - Check that prerequisites are met
 *    - Ensure user has sufficient permissions
 * 
 * If integration is not running:
 *    - Verify configuration values are correct
 *    - Check external system connectivity
 *    - Review scheduled job status
 *    - Test webhook endpoints manually
 * 
 * For additional support:
 *    - Refer to README.md for detailed documentation
 *    - Review SCHEMA.md for database structure
 *    - Check MANIFEST.md for file descriptions
 *    - Contact support with specific error messages
 * 
 * VERSION: 1.0.0
 * GENERATED: 2026-02-02T15:54:44.498Z
 * 
 * =====================================================================
 */
