/**
 * ServiceNow REST API Deployment Script
 * Generated by InfinitiCode
 * Application: Siveillance Intrusion Integration
 * Scope: x_ic_siveillance
 * Table: x_ic_siveillance_siveillance_intrusion_ci
 */

// ServiceNow instance configuration
const SN_INSTANCE = process.env.SN_INSTANCE || 'lastmile.service-now.com';
const SN_USERNAME = process.env.SN_USERNAME || 'admin';
const SN_PASSWORD = process.env.SN_PASSWORD;

if (!SN_PASSWORD) {
  console.error('SN_PASSWORD environment variable is required');
  process.exit(1);
}

const baseUrl = `https://${SN_INSTANCE}/api/now/table`;
const auth = Buffer.from(`${SN_USERNAME}:${SN_PASSWORD}`).toString('base64');

// REST API helper function
async function createRecord(table, data) {
  try {
    const response = await fetch(`${baseUrl}/${table}`, {
      method: 'POST',
      headers: {
        'Authorization': `Basic ${auth}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data)
    });
    
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    
    const result = await response.json();
    console.log(`✅ Created ${table} record: ${result.result.sys_id}`);
    return result.result;
  } catch (error) {
    console.error(`❌ Failed to create ${table}:`, error.message);
    throw error;
  }
}

// Main deployment function
async function deployApplication() {
  console.log('🚀 Deploying Siveillance Intrusion Integration...');
  
  try {
    // 1. Create application
    const app = await createRecord('sys_app', {
      name: 'Siveillance Intrusion Integration',
      scope: 'x_ic_siveillance',
      vendor: 'Last Mile Inc.',
      version: '1.0.0',
      short_description: 'ServiceNow integration package',
      active: true,
      can_edit_in_studio: true
    });
    
    // 2. Create table
    const table = await createRecord('sys_db_object', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      label: 'Siveillance Intrusion Integration CI',
      super_class: 'cmdb_ci_ot_field_device'
    });
    
    // 3. Create fields
    
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_systemid',
      column_label: 'systemId',
      internal_type: 'string',
      max_length: 100,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_systemname',
      column_label: 'systemName',
      internal_type: 'string',
      max_length: 100,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_systemversion',
      column_label: 'systemVersion',
      internal_type: 'string',
      max_length: 100,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_kernelversion',
      column_label: 'kernelVersion',
      internal_type: 'string',
      max_length: 100,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_equipmentnumber',
      column_label: 'equipmentNumber',
      internal_type: 'string',
      max_length: 100,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_countrycode',
      column_label: 'countryCode',
      internal_type: 'string',
      max_length: 100,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_systemstatus',
      column_label: 'systemStatus',
      internal_type: 'string',
      max_length: 100,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_busamount',
      column_label: 'busAmount',
      internal_type: 'integer',
      max_length: 40,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_controlpanelcount',
      column_label: 'controlPanelCount',
      internal_type: 'integer',
      max_length: 40,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_devicecount',
      column_label: 'deviceCount',
      internal_type: 'integer',
      max_length: 40,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_inputcount',
      column_label: 'inputCount',
      internal_type: 'integer',
      max_length: 40,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_outputcount',
      column_label: 'outputCount',
      internal_type: 'integer',
      max_length: 40,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_areacount',
      column_label: 'areaCount',
      internal_type: 'integer',
      max_length: 40,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_lastsystemstart',
      column_label: 'lastSystemStart',
      internal_type: 'glide_date_time',
      max_length: 100,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_licensedateutc',
      column_label: 'licenseDateUtc',
      internal_type: 'glide_date_time',
      max_length: 100,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_availablediskkb',
      column_label: 'availableDiskKb',
      internal_type: 'integer',
      max_length: 40,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      element: 'u_availableflashkb',
      column_label: 'availableFlashKb',
      internal_type: 'integer',
      max_length: 40,
      mandatory: false
    });
    
    // 4. Create navigation module
    await createRecord('sys_app_module', {
      title: 'Siveillance Intrusion Integration CIs',
      name: 'x_ic_siveillance_siveillance_intrusion_ci',
      link_type: 'LIST',
      query: 'sys_class_name=x_ic_siveillance_siveillance_intrusion_ci'
    });
    
    console.log('✅ Deployment completed successfully!');
    console.log(`📋 Application: ${app.name} (${app.scope})`);
    console.log(`📋 Table: x_ic_siveillance_siveillance_intrusion_ci`);
    console.log(`📋 Fields: 17 custom fields created`);
    
  } catch (error) {
    console.error('💥 Deployment failed:', error.message);
    process.exit(1);
  }
}

// Run deployment
deployApplication();
