/*
***************
*
* This file generated by Last Mile Inc. and Infiniticode. All rights reserved.
*
* Fluent for: Siveillance_Intrusion
* Description: ServiceNow integration generated from siveillance-intrusion-integration.yaml
* Type: 
* Platform: Siemens
* Tags: 
* Integration ID: gen-1770047684450-siveillance-intrusion-integration
* Company: Siemens
* YAML Version: 1.0.0
* Generated At: 2026-02-02T15:54:44.490Z
* Generator: InfinitiCode Gemini Fluent Generator
* LLM: vertex
*
***************
*/

import React, { useMemo, useState } from 'react';

interface Step { title: string; body: React.ReactNode; }

export const GuidedSetup: React.FC = () => {
  const defaults = useMemo(() => ({
    "SN_INSTANCE": "",
    "SN_API_KEY": "",
    "SIVEILLANCE_API_KEY": "",
    "SIVEILLANCE_PARTITION_ID": "",
    "SYNC_INTERVAL_SECONDS": 3600,
    "ENABLE_INCIDENT_CORRELATION": true,
  }), []);
  const [values, setValues] = useState<Record<string, string>>(defaults as Record<string, string>);
  const [status, setStatus] = useState<string>('');
  const onChange = (k: string, v: string) => setValues(prev => ({ ...prev, [k]: v }));
  async function apply() {
    try {
      setStatus('Applying...');
      await fetch('/api/config/apply', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ values }) });
      setStatus('Saved.');
    } catch (e) { setStatus('Failed to save'); }
  }
  const steps: Step[] = [
    { title: 'Welcome', body: <p>We will apply default settings and let you review them.</p> },
    { title: 'Configuration', body: (
      <form onSubmit={(e) => { e.preventDefault(); void apply(); }}>
        <div style={{ display: 'flex', gap: 12, padding: '8px 0', borderBottom: '1px solid #eee' }}>
          <label style={{ width: 220, fontWeight: 600 }} htmlFor="SN_INSTANCE">SN_INSTANCE</label>
          <input id="SN_INSTANCE" style={{ flex: 1 }} value={values["SN_INSTANCE"] ?? ''} onChange={(e) => onChange("SN_INSTANCE", e.target.value)} />
        </div>
        <div style={{ display: 'flex', gap: 12, padding: '8px 0', borderBottom: '1px solid #eee' }}>
          <label style={{ width: 220, fontWeight: 600 }} htmlFor="SN_API_KEY">SN_API_KEY</label>
          <input id="SN_API_KEY" style={{ flex: 1 }} value={values["SN_API_KEY"] ?? ''} onChange={(e) => onChange("SN_API_KEY", e.target.value)} />
        </div>
        <div style={{ display: 'flex', gap: 12, padding: '8px 0', borderBottom: '1px solid #eee' }}>
          <label style={{ width: 220, fontWeight: 600 }} htmlFor="SIVEILLANCE_API_KEY">SIVEILLANCE_API_KEY</label>
          <input id="SIVEILLANCE_API_KEY" style={{ flex: 1 }} value={values["SIVEILLANCE_API_KEY"] ?? ''} onChange={(e) => onChange("SIVEILLANCE_API_KEY", e.target.value)} />
        </div>
        <div style={{ display: 'flex', gap: 12, padding: '8px 0', borderBottom: '1px solid #eee' }}>
          <label style={{ width: 220, fontWeight: 600 }} htmlFor="SIVEILLANCE_PARTITION_ID">SIVEILLANCE_PARTITION_ID</label>
          <input id="SIVEILLANCE_PARTITION_ID" style={{ flex: 1 }} value={values["SIVEILLANCE_PARTITION_ID"] ?? ''} onChange={(e) => onChange("SIVEILLANCE_PARTITION_ID", e.target.value)} />
        </div>
        <div style={{ display: 'flex', gap: 12, padding: '8px 0', borderBottom: '1px solid #eee' }}>
          <label style={{ width: 220, fontWeight: 600 }} htmlFor="SYNC_INTERVAL_SECONDS">SYNC_INTERVAL_SECONDS</label>
          <input id="SYNC_INTERVAL_SECONDS" style={{ flex: 1 }} value={values["SYNC_INTERVAL_SECONDS"] ?? ''} onChange={(e) => onChange("SYNC_INTERVAL_SECONDS", e.target.value)} />
        </div>
        <div style={{ display: 'flex', gap: 12, padding: '8px 0', borderBottom: '1px solid #eee' }}>
          <label style={{ width: 220, fontWeight: 600 }} htmlFor="ENABLE_INCIDENT_CORRELATION">ENABLE_INCIDENT_CORRELATION</label>
          <input id="ENABLE_INCIDENT_CORRELATION" style={{ flex: 1 }} value={values["ENABLE_INCIDENT_CORRELATION"] ?? ''} onChange={(e) => onChange("ENABLE_INCIDENT_CORRELATION", e.target.value)} />
        </div>
        <div style={{ marginTop: 12, display: 'flex', gap: 8 }}>
          <button type='submit'>Apply</button>
          <span style={{ opacity: 0.7 }}>{status}</span>
        </div>
      </form>
    ) },
    { title: 'Finish', body: <p>Save your changes and test connectivity.</p> }
  ];
  const [i, setI] = useState(0);
  return (
    <div style={{ padding: 24 }}>
      <h1 style={{ fontSize: 20, marginBottom: 8 }}>Guided Setup</h1>
      <ol style={{ display: 'flex', gap: 8, marginBottom: 16 }}>{steps.map((s, idx) => (<li key={idx} style={{ fontWeight: idx===i?600:400 }}>{idx+1}. {s.title}</li>))}</ol>
      <div style={{ padding: 16, border: '1px solid #eee', borderRadius: 6 }}>{steps[i].body}</div>
      <div style={{ marginTop: 12, display: 'flex', gap: 8 }}>
        <button onClick={() => setI(Math.max(0, i-1))} disabled={i===0}>Back</button>
        <button onClick={() => setI(Math.min(steps.length-1, i+1))} disabled={i===steps.length-1}>Next</button>
      </div>
    </div>
  );
};
