/*
***************
*
* This file generated by Last Mile Inc. and Infiniticode. All rights reserved.
*
* Fluent for: Siveillance_Intrusion
* Description: ServiceNow integration generated from siveillance-intrusion-integration.yaml
* Type: 
* Platform: Siemens
* Tags: 
* Integration ID: gen-1770047684450-siveillance-intrusion-integration
* Company: Siemens
* YAML Version: 1.0.0
* Generated At: 2026-02-02T15:54:44.490Z
* Generator: InfinitiCode Gemini Fluent Generator
* LLM: vertex
*
***************
*/

import { configSchema, getDefaultConfig } from './configSchema';

/**
 * Post-install seeding for configuration variables.
 * Creates sys_properties entries prefixed by app scope.
 */
export async function postInstall(sn: any, scope: string): Promise<{ ok: boolean; created: number; errors?: number }>{
  let created = 0;
  let errors = 0;
  const defaults = getDefaultConfig();
  for (const v of configSchema) {
    const name = (scope ? scope + '.' : '') + v.key;
    try {
      await sn.createProperty({
        name,
        type: v.type || 'string',
        description: v.description || '',
        value: String(defaults[v.key] ?? ''),
        isSecure: !!v.secret
      });
      created++;
    } catch (e) {
      errors++;
      try { sn.logger?.error?.('[Installer] Failed to create property ' + name + ': ' + (e instanceof Error ? e.message : String(e))); } catch {}
    }
  }
  try { sn.logger?.info?.('[Installer] postInstall complete: ' + created + ' properties created'); } catch {}
  return { ok: errors === 0, created, ...(errors ? { errors } : {}) };
}
