/*
***************
*
* This file generated by Last Mile Inc. and Infiniticode. All rights reserved.
*
* Fluent for: Siveillance_Intrusion
* Description: ServiceNow integration generated from siveillance-intrusion-integration.yaml
* Type: 
* Platform: Siemens
* Tags: 
* Integration ID: gen-1770047684450-siveillance-intrusion-integration
* Company: Siemens
* YAML Version: 1.0.0
* Generated At: 2026-02-02T15:54:44.490Z
* Generator: InfinitiCode Gemini Fluent Generator
* LLM: vertex
*
***************
*/

import { configSchema } from './configSchema';

/** Apply overrides to sys_properties with scope prefix */
export async function applyConfigOverrides(sn: any, scope: string, values: Record<string, unknown>): Promise<{ ok: boolean; updated: number; errors?: number }>{
  let updated = 0;
  let errors = 0;
  for (const v of configSchema) {
    const name = (scope ? scope + '.' : '') + v.key;
    const val = values[v.key];
    try {
      // Prefer update (idempotent); create if missing
      try { await sn.updateProperty({ name, value: String(val ?? '') }); } catch { await sn.createProperty({ name, value: String(val ?? '') }); }
      updated++;
    } catch (e) {
      errors++;
      try { sn.logger?.error?.('[Installer] Failed to apply ' + name + ': ' + (e instanceof Error ? e.message : String(e))); } catch {}
    }
  }
  try { sn.logger?.info?.('[Installer] applyConfigOverrides complete: ' + updated + ' properties updated'); } catch {}
  return { ok: errors === 0, updated, ...(errors ? { errors } : {}) };
}
