/*
***************
*
* This file generated by Last Mile Inc. and Infiniticode. All rights reserved.
*
* Fluent for: Siveillance_Intrusion
* Description: ServiceNow integration generated from siveillance-intrusion-integration.yaml
* Type: 
* Platform: Siemens
* Tags: 
* Integration ID: gen-1770047684450-siveillance-intrusion-integration
* Company: Siemens
* YAML Version: 1.0.0
* Generated At: 2026-02-02T15:54:44.490Z
* Generator: InfinitiCode Gemini Fluent Generator
* LLM: vertex
*
***************
*/

export interface ConfigVar {
  key: string;
  type?: string;
  description?: string;
  secret?: boolean;
  default?: unknown;
}

export const configSchema: ReadonlyArray<ConfigVar> = [
  {
    "key": "SN_INSTANCE",
    "type": "string",
    "secret": false,
    "description": "ServiceNow instance URL (e.g., https://dev12345.service-now.com)"
  },
  {
    "key": "SN_API_KEY",
    "type": "string",
    "secret": true,
    "description": "ServiceNow REST API authentication key"
  },
  {
    "key": "SIVEILLANCE_API_KEY",
    "type": "string",
    "secret": true,
    "description": "Siveillance API bearer token"
  },
  {
    "key": "SIVEILLANCE_PARTITION_ID",
    "type": "string",
    "secret": false,
    "description": "Siveillance partition identifier"
  },
  {
    "key": "SYNC_INTERVAL_SECONDS",
    "type": "integer",
    "default": 3600,
    "secret": false,
    "description": "How often to sync data from Siveillance (in seconds)"
  },
  {
    "key": "ENABLE_INCIDENT_CORRELATION",
    "type": "boolean",
    "default": true,
    "secret": false,
    "description": "Enable automatic incident correlation with security events"
  }
] as const;

export function getDefaultConfig(): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const v of configSchema) { out[v.key] = v.default ?? null; }
  return out;
}
