/*
***************
*
* This file generated by Last Mile Inc. and Infiniticode. All rights reserved.
*
* Fluent for: Siveillance_Intrusion
* Description: ServiceNow integration generated from siveillance-intrusion-integration.yaml
* Type: 
* Platform: Siemens
* Tags: 
* Integration ID: gen-1770047684450-siveillance-intrusion-integration
* Company: Siemens
* YAML Version: 1.0.0
* Generated At: 2026-02-02T15:54:44.490Z
* Generator: InfinitiCode Gemini Fluent Generator
* LLM: vertex
*
***************
*/

import React from 'react';

interface RowProps { label: string; value: string; }
const Row: React.FC<RowProps> = ({ label, value }) => (
  <div style={{ display: 'flex', gap: 12, padding: '8px 0', borderBottom: '1px solid #eee' }}>
    <div style={{ width: 220, fontWeight: 600 }}>{label}</div>
    <div style={{ opacity: 0.9 }}>{value}</div>
  </div>
);

export const ConfigPage: React.FC = () => {
  return (
    <div style={{ padding: 24 }}>
      <h1 style={{ fontSize: 20, marginBottom: 8 }}>Configuration</h1>
      <p style={{ margin: 0, opacity: 0.8 }}>Review and update values after install in your instance.</p>
      <div style={{ marginTop: 16 }}>
        <Row label={"SN_INSTANCE"} value={""} />
        <Row label={"SN_API_KEY"} value={""} />
        <Row label={"SIVEILLANCE_API_KEY"} value={""} />
        <Row label={"SIVEILLANCE_PARTITION_ID"} value={""} />
        <Row label={"SYNC_INTERVAL_SECONDS"} value={"3600"} />
        <Row label={"ENABLE_INCIDENT_CORRELATION"} value={"true"} />
      </div>
    </div>
  );
};
